name: Build Docker Image
run-name: ${{ github.actor }} is building docker image ðŸš€
on:
  push:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Docker image
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          TAG=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/marimo
          
          docker build \
            -t $IMAGE_NAME:$TIMESTAMP \
            -t $IMAGE_NAME:$RELEASE_TAG \
            -t $IMAGE_NAME:latest \
            -f docker/Dockerfile .
          
          docker push $IMAGE_NAME:$TIMESTAMP
          docker push $IMAGE_NAME:$RELEASE_TAG
          docker push $IMAGE_NAME:latest
          
          echo "âœ… Successfully pushed three tags: $TIMESTAMP, $RELEASE_TAG, latest"
