name: Build Docker Image
run-name: ${{ github.actor }} is building docker image ðŸš€
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker image
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          TAG=$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          IMAGE_NAME=$DOCKER_USERNAME/marimo
          
          docker build \
            -t $IMAGE_NAME:$TIMESTAMP \
            -t $IMAGE_NAME:$TAG \
            -t $IMAGE_NAME:latest \
            -f docker/Dockerfile .
          
          docker push $IMAGE_NAME:$TIMESTAMP
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
          
          echo "âœ… Successfully pushed three tags: $TIMESTAMP, $TAG, latest"
